title: Like a complete unknown
name: Rob O'Leary
author: Rob O'Leary
email: robjoeol@gmail.com
phone: (+49) 1 523 476 7526
brand: Rob O'Leary
headline: Designer, Explorer, Humanist
description: Navigate with your brightest ideas
copyright: ©Rob O'Leary
url: https://robole.github.io/
github: https://github.com/robole/
codepen: https://codepen.io/robjoeol/
markdown: kramdown
highlighter: rouge
include: ['_pages', '.htaccess']
tag_page: '/blog/tags'

# Disqus Comments
disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    shortname: robole-github-io

plugins:
  - jemoji
  - jekyll-feed
  - jekyll-gist
