title: Personal Website
name: Rob O'Leary
email: robjoeol@gmail.com
phone: (+49) 1 523 476 7526
brand: Rob O'Leary
headline: Designer, Explorer and Humanist
description: Rob O'Leary Independent Analyst Programmer Berlin
copyright: 2012-2017 Rob O'Leary, All Rights Reserved.
github: https://github.com/robole/
codepen: https://codepen.io/robjoeol/
markdown: kramdown
include: ['_pages']
tag_page: '/blog/tags'
disqus_short_name: 'your_short_name' # leave blank if you don't want disqus
