title: Like a complete unknown
name: Rob O'Leary
author: Rob O'Leary
email: robjoeol@gmail.com
phone: (+49) 1 523 476 7526
brand: Rob O'Leary
headline: Designer, Explorer, Humanist
description: Lighten your head and fill your heart using ideas as a map to
a better future.
copyright: ©Rob O'Leary, All Rights Reserved.
url: https://robole.github.io/
github: https://github.com/robole/
codepen: https://codepen.io/robjoeol/
markdown: kramdown
include: ['_pages']
tag_page: '/blog/tags'

# Disqus Comments
disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    shortname: robole-github-io

goodreads:
  userid: 15065423-rob
  api_key: RBUy1EBMk4WTM53sJZVDQ

plugins:
  - jemoji
  - jekyll-feed
