title: Personal Website
name: Rob O'Leary
email: robjoeol@gmail.com
phone: (+49) 1 523 476 7526
brand: Rob O'Leary
headline: Designer, Explorer and Humanist
description: Rob O'Leary Digital Nomad
copyright: 2012-2017 Rob O'Leary, All Rights Reserved.
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
include: ['_pages']
